apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental
  labels:
    app: rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental
  template:
    metadata:
      labels:
        app: rental
        sidecar.istio.io/inject: "true" # Pod 레이블 추가
    spec:
      containers:
        - name: rental
          image: "user13.azurecr.io/rental:latest"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: RENTAL_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config-dev
                  key: RENTAL_LOG_LEVEL
          volumeMounts:
            - mountPath: "/mnt/data"
              name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile
